<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-BGS5S7GJ" ignored="0" name="CRM系统接口测试" tests="28" failures="19" timestamp="22 四月 2020 12:20:56 GMT" time="5.542" errors="0">
  <testcase name="test001_login" time="1.227" classname="com.auto.api0401.AddCustomerTest"/>
  <testcase name="test002_addCustomer" time="2.426" classname="com.auto.api0401.AddCustomerTest"/>
  <testcase name="test002_login" time="0.016" classname="com.auto.api0401.AddCustomerTest"/>
  <testcase name="test003_addCustomer" time="0.106" classname="com.auto.api0401.AddCustomerTest"/>
  <testcase name="test003_login" time="0.016" classname="com.auto.api0401.AddCustomerTest"/>
  <testcase name="test004_addCustomer" time="0.067" classname="com.auto.api0401.AddCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.auto.api0401.AddCustomerTest.test004_addCustomer(AddCustomerTest.java:133)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- test004_addCustomer -->
  <testcase name="test005_addCustomer" time="0.057" classname="com.auto.api0401.AddCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.auto.api0401.AddCustomerTest.test005_addCustomer(AddCustomerTest.java:138)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- test005_addCustomer -->
  <testcase name="test006_addCustomer" time="0.043" classname="com.auto.api0401.AddCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.auto.api0401.AddCustomerTest.test006_addCustomer(AddCustomerTest.java:143)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- test006_addCustomer -->
  <testcase name="test007_addCustomer" time="0.051" classname="com.auto.api0401.AddCustomerTest"/>
  <testcase name="test007_addCustomer" time="0.044" classname="com.auto.api0401.AddCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.auto.api0401.AddCustomerTest.test007_addCustomer(AddCustomerTest.java:156)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- test007_addCustomer -->
  <testcase name="test007_addCustomer" time="0.057" classname="com.auto.api0401.AddCustomerTest"/>
  <testcase name="test007_addCustomer" time="0.04" classname="com.auto.api0401.AddCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.auto.api0401.AddCustomerTest.test007_addCustomer(AddCustomerTest.java:156)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- test007_addCustomer -->
  <testcase name="test007_addCustomer" time="0.046" classname="com.auto.api0401.AddCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.auto.api0401.AddCustomerTest.test007_addCustomer(AddCustomerTest.java:156)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- test007_addCustomer -->
  <testcase name="test007_addCustomer" time="0.051" classname="com.auto.api0401.AddCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.auto.api0401.AddCustomerTest.test007_addCustomer(AddCustomerTest.java:156)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- test007_addCustomer -->
  <testcase name="test007_addCustomer" time="0.086" classname="com.auto.api0401.AddCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.auto.api0401.AddCustomerTest.test007_addCustomer(AddCustomerTest.java:156)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- test007_addCustomer -->
  <testcase name="test007_addCustomer" time="0.076" classname="com.auto.api0401.AddCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.auto.api0401.AddCustomerTest.test007_addCustomer(AddCustomerTest.java:156)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- test007_addCustomer -->
  <testcase name="test007_addCustomer" time="0.068" classname="com.auto.api0401.AddCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.auto.api0401.AddCustomerTest.test007_addCustomer(AddCustomerTest.java:156)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- test007_addCustomer -->
  <testcase name="test007_addCustomer" time="0.082" classname="com.auto.api0401.AddCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.auto.api0401.AddCustomerTest.test007_addCustomer(AddCustomerTest.java:156)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- test007_addCustomer -->
  <testcase name="test007_addCustomer" time="0.051" classname="com.auto.api0401.AddCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.auto.api0401.AddCustomerTest.test007_addCustomer(AddCustomerTest.java:156)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- test007_addCustomer -->
  <testcase name="test008_addCustomer" time="0.101" classname="com.auto.api0401.AddCustomerTest"/>
  <testcase name="test001_addContacts" time="0.062" classname="com.auto.api0401.AddContactsTest"/>
  <testcase name="test001_addProduct" time="0.069" classname="com.auto.api0401.AddProductTest">
    <failure type="java.lang.AssertionError" message="expected [{&amp;quot;code&amp;quot;:0}] but found [{&amp;quot;code&amp;quot;:500,&amp;quot;msg&amp;quot;:&amp;quot;产品编号已存在，请校对后再添加！&amp;quot;}]">
      <![CDATA[java.lang.AssertionError: expected [{"code":0}] but found [{"code":500,"msg":"产品编号已存在，请校对后再添加！"}]
at com.auto.api0401.AddProductTest.test001_addProduct(AddProductTest.java:45)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- test001_addProduct -->
  <testcase name="test002_addProduct" time="0.048" classname="com.auto.api0401.AddProductTest">
    <failure type="java.lang.AssertionError" message="expected [{&amp;quot;code&amp;quot;:0}] but found [{&amp;quot;code&amp;quot;:500,&amp;quot;msg&amp;quot;:&amp;quot;产品编号已存在，请校对后再添加！&amp;quot;}]">
      <![CDATA[java.lang.AssertionError: expected [{"code":0}] but found [{"code":500,"msg":"产品编号已存在，请校对后再添加！"}]
at com.auto.api0401.AddProductTest.test002_addProduct(AddProductTest.java:59)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- test002_addProduct -->
  <testcase name="test003_addProduct" time="0.034" classname="com.auto.api0401.AddProductTest">
    <failure type="java.lang.AssertionError" message="expected [{&amp;quot;code&amp;quot;:1}] but found [{&amp;quot;code&amp;quot;:500,&amp;quot;msg&amp;quot;:&amp;quot;产品编号已存在，请校对后再添加！&amp;quot;}]">
      <![CDATA[java.lang.AssertionError: expected [{"code":1}] but found [{"code":500,"msg":"产品编号已存在，请校对后再添加！"}]
at com.auto.api0401.AddProductTest.test003_addProduct(AddProductTest.java:72)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- test003_addProduct -->
  <testcase name="test004_addProduct" time="0.032" classname="com.auto.api0401.AddProductTest">
    <failure type="java.lang.AssertionError" message="expected [{&amp;quot;code&amp;quot;:1}] but found [{&amp;quot;code&amp;quot;:500,&amp;quot;msg&amp;quot;:&amp;quot;产品编号已存在，请校对后再添加！&amp;quot;}]">
      <![CDATA[java.lang.AssertionError: expected [{"code":1}] but found [{"code":500,"msg":"产品编号已存在，请校对后再添加！"}]
at com.auto.api0401.AddProductTest.test004_addProduct(AddProductTest.java:85)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- test004_addProduct -->
  <testcase name="test005_addProduct" time="0.039" classname="com.auto.api0401.AddProductTest">
    <failure type="java.lang.AssertionError" message="expected [{&amp;quot;code&amp;quot;:1}] but found [{&amp;quot;code&amp;quot;:500,&amp;quot;msg&amp;quot;:&amp;quot;产品编号已存在，请校对后再添加！&amp;quot;}]">
      <![CDATA[java.lang.AssertionError: expected [{"code":1}] but found [{"code":500,"msg":"产品编号已存在，请校对后再添加！"}]
at com.auto.api0401.AddProductTest.test005_addProduct(AddProductTest.java:98)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- test005_addProduct -->
  <testcase name="test006_addProduct" time="0.062" classname="com.auto.api0401.AddProductTest">
    <failure type="java.lang.AssertionError" message="expected [{&amp;quot;code&amp;quot;:1}] but found [{&amp;quot;code&amp;quot;:500,&amp;quot;msg&amp;quot;:&amp;quot;服务器响应异常&amp;quot;}]">
      <![CDATA[java.lang.AssertionError: expected [{"code":1}] but found [{"code":500,"msg":"服务器响应异常"}]
at com.auto.api0401.AddProductTest.test006_addProduct(AddProductTest.java:111)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- test006_addProduct -->
  <testcase name="test007_addProduct" time="0.052" classname="com.auto.api0401.AddProductTest">
    <failure type="java.lang.AssertionError" message="expected [{&amp;quot;code&amp;quot;:0}] but found [{&amp;quot;code&amp;quot;:500,&amp;quot;msg&amp;quot;:&amp;quot;产品编号已存在，请校对后再添加！&amp;quot;}]">
      <![CDATA[java.lang.AssertionError: expected [{"code":0}] but found [{"code":500,"msg":"产品编号已存在，请校对后再添加！"}]
at com.auto.api0401.AddProductTest.test007_addProduct(AddProductTest.java:126)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- test007_addProduct -->
</testsuite> <!-- CRM系统接口测试 -->
