<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-BGS5S7GJ" ignored="0" name="javamall管理员接口测试" tests="25" failures="14" timestamp="25 三月 2020 08:56:15 GMT" time="4.915" errors="0">
  <testcase name="test001_addManager" time="1.404" classname="com.auto.project1.JavaMallTests20200215"/>
  <testcase name="test001_addManager" time="0.149" classname="com.auto.project1.JavaMallTests20200215"/>
  <testcase name="test001_addManager" time="0.146" classname="com.auto.project1.JavaMallTests20200215"/>
  <testcase name="test001_addManager" time="0.143" classname="com.auto.project1.JavaMallTests20200215"/>
  <testcase name="test001_addManager" time="0.154" classname="com.auto.project1.JavaMallTests20200215"/>
  <testcase name="test001_addManager" time="0.13" classname="com.auto.project1.JavaMallTests20200215">
    <failure type="java.lang.AssertionError" message="用户重复失败 expected [用户已存在] but found [新增管理员成功]">
      <![CDATA[java.lang.AssertionError: 用户重复失败 expected [用户已存在] but found [新增管理员成功]
at com.auto.project1.JavaMallTests20200215.test001_addManager(JavaMallTests20200215.java:59)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- test001_addManager -->
  <testcase name="test001_addManager" time="0.142" classname="com.auto.project1.JavaMallTests20200215">
    <failure type="java.lang.AssertionError" message="用户名为空失败 expected [失败] but found [新增管理员成功]">
      <![CDATA[java.lang.AssertionError: 用户名为空失败 expected [失败] but found [新增管理员成功]
at com.auto.project1.JavaMallTests20200215.test001_addManager(JavaMallTests20200215.java:59)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- test001_addManager -->
  <testcase name="test001_addManager" time="0.152" classname="com.auto.project1.JavaMallTests20200215">
    <failure type="java.lang.AssertionError" message="密码为空失败 expected [失败] but found [新增管理员成功]">
      <![CDATA[java.lang.AssertionError: 密码为空失败 expected [失败] but found [新增管理员成功]
at com.auto.project1.JavaMallTests20200215.test001_addManager(JavaMallTests20200215.java:59)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- test001_addManager -->
  <testcase name="test001_addManager" time="0.177" classname="com.auto.project1.JavaMallTests20200215">
    <failure type="java.lang.AssertionError" message="管理员类型为空失败 expected [失败] but found [新增管理员成功]">
      <![CDATA[java.lang.AssertionError: 管理员类型为空失败 expected [失败] but found [新增管理员成功]
at com.auto.project1.JavaMallTests20200215.test001_addManager(JavaMallTests20200215.java:59)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- test001_addManager -->
  <testcase name="test001_addManager" time="0.155" classname="com.auto.project1.JavaMallTests20200215">
    <failure type="java.lang.AssertionError" message="角色类型不存在失败 expected [失败] but found [新增管理员成功]">
      <![CDATA[java.lang.AssertionError: 角色类型不存在失败 expected [失败] but found [新增管理员成功]
at com.auto.project1.JavaMallTests20200215.test001_addManager(JavaMallTests20200215.java:59)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- test001_addManager -->
  <testcase name="test001_addManager" time="0.137" classname="com.auto.project1.JavaMallTests20200215">
    <failure type="java.lang.AssertionError" message="管理员类型不存在失败 expected [失败] but found [新增管理员成功]">
      <![CDATA[java.lang.AssertionError: 管理员类型不存在失败 expected [失败] but found [新增管理员成功]
at com.auto.project1.JavaMallTests20200215.test001_addManager(JavaMallTests20200215.java:59)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- test001_addManager -->
  <testcase name="test001_addManager" time="0.146" classname="com.auto.project1.JavaMallTests20200215">
    <failure type="java.lang.AssertionError" message="状态类型不存在失败 expected [失败] but found [新增管理员成功]">
      <![CDATA[java.lang.AssertionError: 状态类型不存在失败 expected [失败] but found [新增管理员成功]
at com.auto.project1.JavaMallTests20200215.test001_addManager(JavaMallTests20200215.java:59)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- test001_addManager -->
  <testcase name="test002_modifyManager" time="0.167" classname="com.auto.project1.JavaMallTests20200215"/>
  <testcase name="test002_modifyManager" time="0.162" classname="com.auto.project1.JavaMallTests20200215"/>
  <testcase name="test002_modifyManager" time="0.139" classname="com.auto.project1.JavaMallTests20200215"/>
  <testcase name="test002_modifyManager" time="0.103" classname="com.auto.project1.JavaMallTests20200215"/>
  <testcase name="test002_modifyManager" time="0.099" classname="com.auto.project1.JavaMallTests20200215"/>
  <testcase name="test002_modifyManager" time="0.104" classname="com.auto.project1.JavaMallTests20200215">
    <failure type="java.lang.AssertionError" message="用户重复失败 expected [用户已存在] but found [修改管理员成功]">
      <![CDATA[java.lang.AssertionError: 用户重复失败 expected [用户已存在] but found [修改管理员成功]
at com.auto.project1.JavaMallTests20200215.test002_modifyManager(JavaMallTests20200215.java:102)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- test002_modifyManager -->
  <testcase name="test002_modifyManager" time="0.114" classname="com.auto.project1.JavaMallTests20200215">
    <failure type="java.lang.AssertionError" message="用户名为空失败 expected [失败] but found [修改管理员成功]">
      <![CDATA[java.lang.AssertionError: 用户名为空失败 expected [失败] but found [修改管理员成功]
at com.auto.project1.JavaMallTests20200215.test002_modifyManager(JavaMallTests20200215.java:102)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- test002_modifyManager -->
  <testcase name="test002_modifyManager" time="0.106" classname="com.auto.project1.JavaMallTests20200215">
    <failure type="java.lang.AssertionError" message="密码为空失败 expected [失败] but found [修改管理员成功]">
      <![CDATA[java.lang.AssertionError: 密码为空失败 expected [失败] but found [修改管理员成功]
at com.auto.project1.JavaMallTests20200215.test002_modifyManager(JavaMallTests20200215.java:102)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- test002_modifyManager -->
  <testcase name="test002_modifyManager" time="0.11" classname="com.auto.project1.JavaMallTests20200215">
    <failure type="java.lang.AssertionError" message="管理员类型为空失败 expected [失败] but found [修改管理员成功]">
      <![CDATA[java.lang.AssertionError: 管理员类型为空失败 expected [失败] but found [修改管理员成功]
at com.auto.project1.JavaMallTests20200215.test002_modifyManager(JavaMallTests20200215.java:102)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- test002_modifyManager -->
  <testcase name="test002_modifyManager" time="0.119" classname="com.auto.project1.JavaMallTests20200215">
    <failure type="java.lang.AssertionError" message="角色类型不存在失败 expected [失败] but found [修改管理员成功]">
      <![CDATA[java.lang.AssertionError: 角色类型不存在失败 expected [失败] but found [修改管理员成功]
at com.auto.project1.JavaMallTests20200215.test002_modifyManager(JavaMallTests20200215.java:102)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- test002_modifyManager -->
  <testcase name="test002_modifyManager" time="0.101" classname="com.auto.project1.JavaMallTests20200215">
    <failure type="java.lang.AssertionError" message="管理员类型不存在失败 expected [失败] but found [修改管理员成功]">
      <![CDATA[java.lang.AssertionError: 管理员类型不存在失败 expected [失败] but found [修改管理员成功]
at com.auto.project1.JavaMallTests20200215.test002_modifyManager(JavaMallTests20200215.java:102)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- test002_modifyManager -->
  <testcase name="test002_modifyManager" time="0.105" classname="com.auto.project1.JavaMallTests20200215">
    <failure type="java.lang.AssertionError" message="状态类型不存在失败 expected [失败] but found [修改管理员成功]">
      <![CDATA[java.lang.AssertionError: 状态类型不存在失败 expected [失败] but found [修改管理员成功]
at com.auto.project1.JavaMallTests20200215.test002_modifyManager(JavaMallTests20200215.java:102)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- test002_modifyManager -->
  <testcase name="test003_deleteManager" time="0.016" classname="com.auto.project1.JavaMallTests20200215"/>
</testsuite> <!-- javamall管理员接口测试 -->
